### Link base de teste
GET http://localhost:5227

### Listar todos os animais
GET  http://localhost:5227/api/animais/listar

### Buscar por id
GET http://localhost:5227/api/animais/buscar/{id}
### Cadastrar Animais
POST http://localhost:5227/api/animais/cadastrar
Content-Type: application/json

{
    
    "nome" : "Tamanduá-Bandeira",
    "descricao" : "Mamífero de grande porte, nativo da América do Sul, conhecido por sua cauda longa e espessa que se assemelha a uma bandeira. Sua alimentação é baseada em insetos.",
    "dataNascimento" : "2000-10-26",
    "especie" : "Mamífero da ordem Xenarthra e família Myrmecophagidae",
    "habitat": "ampos abertos, florestas e savanas da América do Sul.",
    "paisDeOrigem": "Brasil"

}   

### Deletar um Animal
DELETE http://localhost:5227/api/animais/deletar/{id}

### Atualizar um Animal
PATCH http://localhost:5227/api/animais/atualizar/{id}
Content-Type: application/json

{
    
    "nome" : "Tamanduá",
    "descricao" : "Mamífero de grande porte, nativo da América do Sul, conhecido por sua cauda longa e espessa que se assemelha a uma bandeira. Sua alimentação é baseada em insetos.",
    "dataNascimento" : "2010-12-01",
    "especie" : "Mamífero da ordem Xenarthra e família Myrmecophagidae",
    "habitat": "Campos abertos, florestas e savanas da América do Sul.",
    "paisDeOrigem": "Brasil"

}  
