
### Link base de teste
GET http://localhost:5227

### Listar todos os animais
GET http://localhost:5227/localhost:5064/api/animail/listar

### Buscar por id
GET http://localhost:5227/localhost:5064/api/animal/buscar/{id}

### Cadastrar Animais
POST http://localhost:5227/localhost:5064/api/animal/cadastrar
Content-Type: application/json

{
    "nome" : "Tamanduá-Bandeira",
    "descricao" : "Mamífero de grande porte, nativo da América do Sul, conhecido por sua cauda longa e espessa que se assemelha a uma bandeira. Sua alimentação é baseada em insetos.",
    "dataNascimento" : "26/10/2000",
    "especie" : "Mamífero da ordem Xenarthra e família Myrmecophagidae",
    "habitat": "ampos abertos, florestas e savanas da América do Sul.",
    "paisDeOrigem": "Brasil",

}   
